CREATE DATABASE IF NOT EXISTS MYCHAT;

USE MYCHAT;

CREATE TABLE AL_USER
(
	AL_USERID INT PRIMARY KEY AUTO_INCREMENT,
    AL_USERNAME VARCHAR(20),
    AL_PASSWORD VARCHAR(20),
    AL_NAME NVARCHAR(40),
    AL_EMAIL VARCHAR(40),
    AL_PHONE VARCHAR(11) not null unique,
    AL_STATUS VARCHAR(20)
);

CREATE TABLE AL_RELA
(
	AL_RELAID INT PRIMARY KEY AUTO_INCREMENT,
    AL_USER1 INT,
    AL_USER2 INT,
    AL_RELA VARCHAR(20)
);

CREATE TABLE AL_GROUP
(
	AL_GROUPID INT PRIMARY KEY AUTO_INCREMENT,
    AL_GROUPNAME NVARCHAR(50),
    AL_NUMBERUSER INT,
    AL_DATE DATETIME
);

CREATE TABLE AL_GROUPDETAIL
(
	AL_DETAILID INT PRIMARY KEY AUTO_INCREMENT,
    AL_USERID INT,
    AL_GROUPID INT
);

CREATE TABLE AL_MESS
(
	AL_MESSID INT PRIMARY KEY AUTO_INCREMENT,
    AL_FROM INT,
    AL_TO INT,
    AL_CONTENT NVARCHAR(1000),
    AL_DATE DATETIME,
    AL_STATUS VARCHAR(20),
    AL_TYPE VARCHAR(20)  -- to group or to user
);

CREATE TABLE AL_FR_REQUEST
(
	AL_RQID INT PRIMARY KEY AUTO_INCREMENT,
    AL_FROM INT,
    AL_TO INT,
    AL_CONTENT NVARCHAR(100),
    AL_DATE_CREATE DATETIME,
    AL_DATE_MODIFIED DATETIME,
    AL_STATUS VARCHAR(20)
);

ALTER TABLE AL_RELA
ADD CONSTRAINT RELA_USER1
FOREIGN KEY (AL_USER1)
REFERENCES AL_USER(AL_USERID);

ALTER TABLE AL_RELA
ADD CONSTRAINT RELA_USER2
FOREIGN KEY (AL_USER2)
REFERENCES AL_USER(AL_USERID);

ALTER TABLE AL_GROUPDETAIL
ADD CONSTRAINT DETAIL_USER
FOREIGN KEY (AL_USERID)
REFERENCES AL_USER(AL_USERID);

ALTER TABLE AL_GROUPDETAIL
ADD CONSTRAINT DETAIL_GROUP
FOREIGN KEY (AL_GROUPID)
REFERENCES AL_GROUP(AL_GROUPID);

ALTER TABLE AL_MESS
ADD CONSTRAINT MESS_USER
FOREIGN KEY (AL_FROM)
REFERENCES AL_USER(AL_USERID);

ALTER TABLE AL_FR_REQUEST
ADD CONSTRAINT RQ_FROM
FOREIGN KEY (AL_FROM)
REFERENCES AL_USER(AL_USERID);

ALTER TABLE AL_FR_REQUEST
ADD CONSTRAINT RQ_TO
FOREIGN KEY (AL_TO)
REFERENCES AL_USER(AL_USERID);
